/*
 * generated by Xtext
 */
package org.cmg.resp.xtext.scellight.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ScelLightUiModule extends org.cmg.resp.xtext.scellight.ui.AbstractScelLightUiModule {
	public ScelLightUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
