/*
 * generated by Xtext
 */
package org.cmg.resp.xtext.scellight.ui.contentassist

import org.cmg.resp.xtext.scellight.ui.contentassist.AbstractScelLightProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ScelLightProposalProvider extends AbstractScelLightProposalProvider {
}
