/*
 * generated by Xtext
 */
package org.cmg.resp.xtext.hlscel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HLScelUiModule extends org.cmg.resp.xtext.hlscel.ui.AbstractHLScelUiModule {
	public HLScelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
