/**
 * generated by Xtext
 */
package org.cmg.resp.xtext.hlscel.ui.labeling;

import org.eclipse.xtext.xbase.ui.labeling.XbaseDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class HLScelDescriptionLabelProvider extends XbaseDescriptionLabelProvider {
}
