/*
 * generated by Xtext
 */
package org.cmg.resp.xtext.scellight.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractScelLightValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.cmg.resp.xtext.scellight.scelLight.ScelLightPackage.eINSTANCE);
		return result;
	}
}
