/*
 * generated by Xtext
 */
package org.cmg.resp.xtext.hlscel;

import org.cmg.resp.xtext.hlscel.compiler.HLScelCompiler;
import org.cmg.resp.xtext.hlscel.types.HLScelTypeComputer;
import org.eclipse.xtext.xbase.compiler.XbaseCompiler;
import org.eclipse.xtext.xbase.typesystem.computation.ITypeComputer;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HLScelRuntimeModule extends org.cmg.resp.xtext.hlscel.AbstractHLScelRuntimeModule {

	@Override
	public Class<? extends ITypeComputer> bindITypeComputer() {
		return HLScelTypeComputer.class;
	}
	
	public Class<? extends XbaseCompiler> bindXbaseCompiler() {
		return HLScelCompiler.class;
	}
	

}
