/*
 * generated by Xtext
 */
package org.cmg.resp.xtext.hlscel.validation

import org.eclipse.xtext.xbase.XExpression
import org.cmg.resp.xtext.hlscel.hLScel.HLScelPutAction
import org.eclipse.emf.ecore.EObject
import org.cmg.resp.xtext.hlscel.hLScel.HLScelGetAction
import org.cmg.resp.xtext.hlscel.hLScel.HLScelGetPAction
import org.cmg.resp.xtext.hlscel.hLScel.HLScelQueryAction
import org.cmg.resp.xtext.hlscel.hLScel.HLScelQueryPAction
import org.cmg.resp.xtext.hlscel.hLScel.HLScelExecAction
import org.cmg.resp.xtext.hlscel.hLScel.HLScelCallAction

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class HLScelValidator extends AbstractHLScelValidator {

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	protected override isValueExpectedRecursive(XExpression expr) {
		if (super.isValueExpectedRecursive(expr)) {
			true
		} else {
			expr.eContainer.anAction 
		}
	}
	
	protected def isAnAction(EObject expr) {
		(expr instanceof HLScelPutAction)
		||(expr instanceof HLScelGetAction)
		||(expr instanceof HLScelGetPAction)
		||(expr instanceof HLScelQueryAction)
		||(expr instanceof HLScelQueryPAction)
		||(expr instanceof HLScelExecAction)
		||(expr instanceof HLScelCallAction)
	}

}
