/*
* generated by Xtext
*/
package org.cmg.resp.xtext.scellight;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ScelLightStandaloneSetup extends ScelLightStandaloneSetupGenerated{

	public static void doSetup() {
		new ScelLightStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

