/*
 * generated by Xtext
 */
package org.cmg.resp.xtext.scellight;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ScelLightRuntimeModule extends org.cmg.resp.xtext.scellight.AbstractScelLightRuntimeModule {

}
