/*
 * generated by Xtext
 */
package org.cmg.resp.xtext.hlscel.ui.contentassist

import org.cmg.resp.xtext.hlscel.ui.contentassist.AbstractHLScelProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class HLScelProposalProvider extends AbstractHLScelProposalProvider {
}
