/**
 * generated by Xtext
 */
package org.cmg.resp.xtext.hlscel.validation;

import org.cmg.resp.xtext.hlscel.validation.AbstractHLScelValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class HLScelValidator extends AbstractHLScelValidator {
}
