/*
* generated by Xtext
*/
package org.cmg.resp.xtext.scellight.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ScelLightAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/cmg/resp/xtext/scellight/parser/antlr/internal/InternalScelLight.tokens");
	}
}
