/*
* generated by Xtext
*/
package org.cmg.resp.xtext.scellight.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.cmg.resp.xtext.scellight.services.ScelLightGrammarAccess;

public class ScelLightParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ScelLightGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.cmg.resp.xtext.scellight.parser.antlr.internal.InternalScelLightParser createParser(XtextTokenStream stream) {
		return new org.cmg.resp.xtext.scellight.parser.antlr.internal.InternalScelLightParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public ScelLightGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ScelLightGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
