/*
* generated by Xtext
*/
package org.cmg.resp.xtext.hlscel.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.cmg.resp.xtext.hlscel.services.HLScelGrammarAccess;

public class HLScelParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private HLScelGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.cmg.resp.xtext.hlscel.parser.antlr.internal.InternalHLScelParser createParser(XtextTokenStream stream) {
		return new org.cmg.resp.xtext.hlscel.parser.antlr.internal.InternalHLScelParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public HLScelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(HLScelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
