/*
* generated by Xtext
*/
package org.cmg.resp.xtext.scellight;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ScelLightUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.cmg.resp.xtext.scellight.ui.internal.ScelLightActivator.getInstance().getInjector("org.cmg.resp.xtext.scellight.ScelLight");
	}
	
}
