/*
* generated by Xtext
*/
package org.cmg.resp.xtext.hlscel;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class HLScelUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.cmg.resp.xtext.hlscel.ui.internal.HLScelActivator.getInstance().getInjector("org.cmg.resp.xtext.hlscel.HLScel");
	}
	
}
