/*
 * generated by Xtext
 */
package org.cmg.resp.xtext.hlscel.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.cmg.resp.xtext.hlscel.ui.internal.HLScelActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HLScelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return HLScelActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return HLScelActivator.getInstance().getInjector(HLScelActivator.ORG_CMG_RESP_XTEXT_HLSCEL_HLSCEL);
	}
	
}
